services:
  logseq:
    image: ghcr.io/logseq/logseq-webapp:latest
    container_name: logseq
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.logseq.rule=Host(`logseq.local.ejsadiarin.com`)"
      - "traefik.http.routers.logseq.entrypoints=https"
      - "traefik.http.routers.logseq.tls=true"
      - "traefik.http.services.logseq.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
