version: 2
global:
  server_name: ejsadiarin.com # Your Matrix Domain
  private_key: /etc/dendrite/matrix_key.pem
  # JetStream is internal message queue
  jetstream:
    storage:
      storage_path: /var/dendrite/jetstream
      
media_api:
  database:
    connection_string: postgres://dendrite:${DB_PASSWORD}@dendrite-postgresql.dendrite.svc:5432/dendrite?sslmode=disable

sync_api:
  database:
    connection_string: postgres://dendrite:${DB_PASSWORD}@dendrite-postgresql.dendrite.svc:5432/dendrite?sslmode=disable

room_server:
  database:
    connection_string: postgres://dendrite:${DB_PASSWORD}@dendrite-postgresql.dendrite.svc:5432/dendrite?sslmode=disable

federation_api:
  database:
    connection_string: postgres://dendrite:${DB_PASSWORD}@dendrite-postgresql.dendrite.svc:5432/dendrite?sslmode=disable

user_api:
  account_database:
    connection_string: postgres://dendrite:${DB_PASSWORD}@dendrite-postgresql.dendrite.svc:5432/dendrite?sslmode=disable

key_server:
  database:
    connection_string: postgres://dendrite:${DB_PASSWORD}@dendrite-postgresql.dendrite.svc:5432/dendrite?sslmode=disable

mscs:
  database:
    connection_string: postgres://dendrite:${DB_PASSWORD}@dendrite-postgresql.dendrite.svc:5432/dendrite?sslmode=disable

app_service_api:
  database:
    connection_string: postgres://dendrite:${DB_PASSWORD}@dendrite-postgresql.dendrite.svc:5432/dendrite?sslmode=disable

relay_api:
  database:
    connection_string: postgres://dendrite:${DB_PASSWORD}@dendrite-postgresql.dendrite.svc:5432/dendrite?sslmode=disable

logging:
  - type: std
    level: info
