---
# Source: kube-vip/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip
  namespace: kube-system
  labels:
    helm.sh/chart: kube-vip-0.9.1
    app.kubernetes.io/name: kube-vip
    app.kubernetes.io/instance: kube-vip
    app.kubernetes.io/version: "v1.0.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: kube-vip/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: kube-vip
rules:
  - apiGroups: [""]
    resources: ["services/status"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["list", "get", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "get", "watch", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["list", "get", "watch", "update", "create"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list", "get", "watch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
---
# Source: kube-vip/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-vip
  labels:
    helm.sh/chart: kube-vip-0.9.1
    app.kubernetes.io/name: kube-vip
    app.kubernetes.io/instance: kube-vip
    app.kubernetes.io/version: "v1.0.1"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-vip
subjects:
- kind: ServiceAccount
  name: kube-vip
  namespace: kube-system
---
# Source: kube-vip/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip
      app.kubernetes.io/instance: kube-vip
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-vip
        app.kubernetes.io/instance: kube-vip
    spec:
      containers:
      - args:
          - manager
        env:
          - name: vip_address
            value: 192.168.70.100
          - name: "cp_enable"
            value: "true"
          - name: "cp_namespace"
            value: "kube-system"
          - name: "lb_enable"
            value: "true"
          - name: "lb_port"
            value: "6443"
          - name: "prometheus_server"
            value: ":2112"
          - name: "svc_election"
            value: "false"
          - name: "svc_enable"
            value: "false"
          - name: "vip_arp"
            value: "true"
          - name: "vip_interface"
            value: "eth0"
          - name: "vip_leaderelection"
            value: "false"
          - name: "vip_subnet"
            value: "32"
        image: ghcr.io/kube-vip/kube-vip:v1.0.1
        imagePullPolicy: IfNotPresent
        name: kube-vip
        resources:
          {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
      hostNetwork: true
      serviceAccountName: kube-vip
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
