apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: element

resources:
  - ns.yaml
  - deployment.yaml
  - httproute.yaml

configMapGenerator:
  - name: element-config
    files:
      - config.json
