services:
  gitea-server:
    image: gitea/gitea:1.22.4
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - USER=git
      - RUN_MODE=prod
      # database
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - DOMAIN=git.local.ejsadiarin.com
      - SSH_DOMAIN=git.local.ejsadiarin.com
      - HTTP_PORT=3000
      - ROOT_URL=https://git.local.ejsadiarin.com
      - SSH_PORT=2222
      - START_SSH_SERVER=false
      - SSH_LISTEN_PORT=22
    restart: unless-stopped
    ports:
      - "2222:22"
    networks:
      - proxy
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`git.local.ejsadiarin.com`)"
      - "traefik.http.routers.gitea.entrypoints=https"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.routers.gitea.service=gitea"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  db:
    image: postgres:14
    container_name: gitea_postgres
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - proxy
    volumes:
      - ./postgres:/var/lib/postgresql/data

networks:
  proxy:
    external: true
