services:
  gitea-server:
    image: gitea/gitea:1.22.4
    container_name: gitea
    environment:
      USER_UID: 1000
      USER_GID: 1000
      # database
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: db:5432
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: gitea
      GITEA__repository__ENABLE_PUSH_CREATE_ORG: "true"
      # server
      GITEA__server__OFFLINE_MODE: "true"
      GITEA__server__ROOT_URL: "https://git.local.ejsadiarin.com/"
      GITEA__server__SSH_PORT: 22
      GITEA__server__START_SSH_SERVER: "true"
      GITEA__server__SSH_LISTEN_PORT: 222
      GITEA__service__DISABLE_REGISTRATION: "true"
      GITEA__service__REQUIRE_SIGNIN_VIEW: "true"
      GITEA__service__DEFAULT_ALLOW_CREATE_ORGANIZATION: "false"
      GITEA__service__DEFAULT_ENABLE_TIMETRACKING: "false"
      GITEA__repository__USE_COMPAT_SSH_URI: "false"
      GITEA__oauth2_client__ENABLE_AUTO_REGISTRATION: "true"
      GITEA__oauth2_client__OPENID_CONNECT_SCOPES: "email profile"
      GITEA__oauth2_client__USERNAME: "email"
      GITEA__openid__ENABLE_OPENID_SIGNIN: "false"
    restart: always
    networks:
      - proxy
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`git.local.ejsadiarin.com`)"
      - "traefik.http.routers.gitea.entrypoints=https"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.routers.gitea.service=gitea"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.gitea-ssh.entrypoints=ssh"
      - "traefik.tcp.routers.gitea-ssh.service=gitea-ssh-svc"
      - "traefik.tcp.services.gitea-ssh-svc.loadbalancer.server.port=222"
    # security_opt:
    # - no-new-privileges:true

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - proxy
    volumes:
      - ./postgres:/var/lib/postgresql/data

networks:
  proxy:
    external: true
