---
services:
  server:
    image: gitea/gitea:1.23.4
    container_name: gitea-server
    environment:
      - USER_UID=1000
      - USER_GID=1000
      # -- Change your database settings here...
      # --> PostgreSQL
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}
      - GITEA__database__NAME=${POSTGRES_DB:?POSTGRES_DB not set}
      - GITEA__database__USER=${POSTGRES_USER:?POSTGRES_USER not set}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}
      # <--
      # <--
      # -- (Optional) Change your server settings here...
      - GITEA__server__SSH_PORT=2221  # <-- (Optional) Replace with your desired SSH port
      - GITEA__server__ROOT_URL=https://gitea.local.ejsadiarin.com  # <-- Replace with your FQDN
    # --> (Optional) When using traefik...
    networks:
      - proxy
    # <--
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2221:22"  # <-- (Optional) Replace with your desired SSH port
      # --> (Optional) When using internal database...
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - traefik.http.services.gitea.loadbalancer.server.scheme=http
      - traefik.http.routers.gitea-https.entrypoints=https
      - traefik.http.routers.gitea-https.rule=Host(`gitea.local.ejsadiarin.com`)  # <-- Replace with your FQDN
      - traefik.http.routers.gitea-https.tls=true
      - traefik.http.routers.gitea-https.tls.certresolver=cloudflare  # <-- Replace with your certresolver
    # <--
    restart: unless-stopped

    # --> When using internal database
  db:
    image: postgres:14
    container_name: gitea-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?POSTGRES_USER not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}
      - POSTGRES_DB=${POSTGRES_DB:?POSTGRES_DB not set}
    networks:
      - proxy
    volumes:
      - ./gitea-db:/var/lib/postgresql/data
    restart: unless-stopped

# --> (Optional) When using traefik...
networks:
  proxy:
    external: true
