services:
  gitea-server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      # - USER=git
      - RUN_MODE=prod
      # database
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - DOMAIN=git.local.ejsadiarin.com
      - HTTP_PORT=3000
      - ROOT_URL=https://git.local.ejsadiarin.com
      - SSH_DOMAIN=git.local.ejsadiarin.com
      - SSH_PORT=222
      - SSH_LISTEN_PORT=22
    restart: always
    # ports:
    #   - "222:22"
    networks:
      - proxy
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`git.local.ejsadiarin.com`)"
      - "traefik.http.routers.gitea.entrypoints=http"
      - "traefik.http.routers.gitea.entrypoints=https"
      # - "traefik.http.routers.gitea.service=gitea"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"

      - "traefik.backend=gitea"
      - "traefik.docker.network=proxy"
      - "traefik.default.protocol=http"
      - "traefik.port=3000"

      - "traefik.http.routers.gitea.tls=true"

      # SSH routing, can't route based on host so anything to port 222 will come to this container
      - "traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.gitea-ssh.entrypoints=gitea_ssh"
      - "traefik.tcp.routers.gitea-ssh.service=gitea-ssh-svc"
      - "traefik.tcp.services.gitea-ssh-svc.loadbalancer.server.port=22"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  db:
    image: postgres:14
    container_name: gitea_postgres
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - proxy
    volumes:
      - ./postgres:/var/lib/postgresql/data

networks:
  proxy:
    external: true
