apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-prometheus-stack

helmCharts:
  - name: prometheus-adapter
    repo: https://prometheus-community.github.io/helm-charts
    version: 5.2.0 # Latest stable
    releaseName: prometheus-adapter
    namespace: kube-prometheus-stack
    valuesFile: values.yaml
    includeCRDs: true

commonAnnotations:
  argocd.argoproj.io/sync-wave: "2" # Deploy after Prometheus is ready
