apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - httproute.yaml
  - deployment.yaml
  - service.yaml
  # - pvc.yaml

namespace: glance
configMapGenerator:
  - name: glance-config
    files:
      - glance.yaml
