# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: glance
  namespace: glance
spec:
  selector:
    app: glance
    app.kubernetes.io/name: glance
  type: ClusterIP
  ports:
    - name: glance
      protocol: TCP
      port: 8080
      targetPort: 8080
      # nodePort: 30001
