services:
  uptime-kuma:
    container_name: uptime_kuma
    image: louislam/uptime-kuma:latest
    volumes:
      - data:/app/data
    restart: always
    networks:
        - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime-kuma.local.ejsadiarin.com`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=https"
      - "traefik.http.routers.uptime-kuma.tls=true"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=8080"

volumes:
  data:

networks:
  proxy:
    external: true

