apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus
  namespace: kube-prometheus-stack
spec:
  parentRefs:
    - name: gateway-internal # must match Gateway's metadata.name
      namespace: gateway
      sectionName: https # must match Gateway's listeners[].name
  hostnames:
    - "prometheus.int.ejsadiarin.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: prometheus-operated
          port: 9090
