# apps/production/traefik-middlewares/allow-iframe.yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/traefik.io/middleware_v1alpha1.json
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: allow-iframe
  namespace: traefik
spec:
  headers:
    contentSecurityPolicy: "frame-ancestors 'self' https://*.local.ejsadiarin.com;"